site_name: RAHA
nav:
  - Home: index.md
  - The team: about.md
  - Design: design.md
  - Presentations: presentations.md
  - Other: other.md
theme:
  name: material
  logo: img/logo.gif
  palette:
    primary: brown
  font:
    text: Maven Pro